# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtDesigner/Main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 894)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(458, 528))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.twCentral = QtWidgets.QTabWidget(self.splitter)
        self.twCentral.setEnabled(True)
        self.twCentral.setTabsClosable(False)
        self.twCentral.setTabBarAutoHide(False)
        self.twCentral.setObjectName("twCentral")
        self.tabProcess = QtWidgets.QWidget()
        self.tabProcess.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabProcess.sizePolicy().hasHeightForWidth())
        self.tabProcess.setSizePolicy(sizePolicy)
        self.tabProcess.setObjectName("tabProcess")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabProcess)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupDemod = QtWidgets.QGroupBox(self.tabProcess)
        self.groupDemod.setObjectName("groupDemod")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupDemod)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.glDemod = QtWidgets.QGridLayout()
        self.glDemod.setObjectName("glDemod")
        self.tbDemodSettings = QtWidgets.QToolButton(self.groupDemod)
        self.tbDemodSettings.setObjectName("tbDemodSettings")
        self.glDemod.addWidget(self.tbDemodSettings, 0, 3, 1, 1)
        self.pbDemodStart = QtWidgets.QPushButton(self.groupDemod)
        self.pbDemodStart.setObjectName("pbDemodStart")
        self.glDemod.addWidget(self.pbDemodStart, 2, 2, 1, 2)
        self.pbDemodOpen = QtWidgets.QPushButton(self.groupDemod)
        self.pbDemodOpen.setObjectName("pbDemodOpen")
        self.glDemod.addWidget(self.pbDemodOpen, 0, 2, 1, 1)
        self.textDemodOutput = QtWidgets.QTextEdit(self.groupDemod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textDemodOutput.sizePolicy().hasHeightForWidth())
        self.textDemodOutput.setSizePolicy(sizePolicy)
        self.textDemodOutput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textDemodOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDemodOutput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDemodOutput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textDemodOutput.setObjectName("textDemodOutput")
        self.glDemod.addWidget(self.textDemodOutput, 1, 1, 1, 1)
        self.pbDemodSelect = QtWidgets.QPushButton(self.groupDemod)
        self.pbDemodSelect.setObjectName("pbDemodSelect")
        self.glDemod.addWidget(self.pbDemodSelect, 1, 2, 1, 1)
        self.textDemodInput = QtWidgets.QTextEdit(self.groupDemod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textDemodInput.sizePolicy().hasHeightForWidth())
        self.textDemodInput.setSizePolicy(sizePolicy)
        self.textDemodInput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textDemodInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDemodInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDemodInput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textDemodInput.setObjectName("textDemodInput")
        self.glDemod.addWidget(self.textDemodInput, 0, 1, 1, 1)
        self.lDemodInput = QtWidgets.QLabel(self.groupDemod)
        self.lDemodInput.setObjectName("lDemodInput")
        self.glDemod.addWidget(self.lDemodInput, 0, 0, 1, 1)
        self.lDemodOuput = QtWidgets.QLabel(self.groupDemod)
        self.lDemodOuput.setObjectName("lDemodOuput")
        self.glDemod.addWidget(self.lDemodOuput, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.glDemod, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupDemod, 0, 0, 1, 1)
        self.groupDecode = QtWidgets.QGroupBox(self.tabProcess)
        self.groupDecode.setObjectName("groupDecode")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupDecode)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.glDecode = QtWidgets.QGridLayout()
        self.glDecode.setObjectName("glDecode")
        self.tbDecodeSettings = QtWidgets.QToolButton(self.groupDecode)
        self.tbDecodeSettings.setObjectName("tbDecodeSettings")
        self.glDecode.addWidget(self.tbDecodeSettings, 0, 3, 1, 1)
        self.pbDecodeStart = QtWidgets.QPushButton(self.groupDecode)
        self.pbDecodeStart.setObjectName("pbDecodeStart")
        self.glDecode.addWidget(self.pbDecodeStart, 2, 2, 1, 2)
        self.pbDecodeOpen = QtWidgets.QPushButton(self.groupDecode)
        self.pbDecodeOpen.setObjectName("pbDecodeOpen")
        self.glDecode.addWidget(self.pbDecodeOpen, 0, 2, 1, 1)
        self.textDecodeOutput = QtWidgets.QTextEdit(self.groupDecode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textDecodeOutput.sizePolicy().hasHeightForWidth())
        self.textDecodeOutput.setSizePolicy(sizePolicy)
        self.textDecodeOutput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textDecodeOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDecodeOutput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDecodeOutput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textDecodeOutput.setObjectName("textDecodeOutput")
        self.glDecode.addWidget(self.textDecodeOutput, 1, 1, 1, 1)
        self.pbDecodeSelect = QtWidgets.QPushButton(self.groupDecode)
        self.pbDecodeSelect.setObjectName("pbDecodeSelect")
        self.glDecode.addWidget(self.pbDecodeSelect, 1, 2, 1, 1)
        self.textDecodeInput = QtWidgets.QTextEdit(self.groupDecode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textDecodeInput.sizePolicy().hasHeightForWidth())
        self.textDecodeInput.setSizePolicy(sizePolicy)
        self.textDecodeInput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textDecodeInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDecodeInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textDecodeInput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textDecodeInput.setObjectName("textDecodeInput")
        self.glDecode.addWidget(self.textDecodeInput, 0, 1, 1, 1)
        self.lDecodeInput = QtWidgets.QLabel(self.groupDecode)
        self.lDecodeInput.setObjectName("lDecodeInput")
        self.glDecode.addWidget(self.lDecodeInput, 0, 0, 1, 1)
        self.lDecodeOutput = QtWidgets.QLabel(self.groupDecode)
        self.lDecodeOutput.setObjectName("lDecodeOutput")
        self.glDecode.addWidget(self.lDecodeOutput, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.glDecode, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupDecode, 1, 0, 1, 1)
        self.groupAnalyze = QtWidgets.QGroupBox(self.tabProcess)
        self.groupAnalyze.setObjectName("groupAnalyze")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupAnalyze)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.glAnalyze = QtWidgets.QGridLayout()
        self.glAnalyze.setObjectName("glAnalyze")
        self.tbAnalyzeSettings = QtWidgets.QToolButton(self.groupAnalyze)
        self.tbAnalyzeSettings.setObjectName("tbAnalyzeSettings")
        self.glAnalyze.addWidget(self.tbAnalyzeSettings, 0, 3, 1, 1)
        self.bpAnalyzeSelect = QtWidgets.QPushButton(self.groupAnalyze)
        self.bpAnalyzeSelect.setEnabled(False)
        self.bpAnalyzeSelect.setObjectName("bpAnalyzeSelect")
        self.glAnalyze.addWidget(self.bpAnalyzeSelect, 1, 2, 1, 1)
        self.lAnalyzeInput = QtWidgets.QLabel(self.groupAnalyze)
        self.lAnalyzeInput.setObjectName("lAnalyzeInput")
        self.glAnalyze.addWidget(self.lAnalyzeInput, 0, 0, 1, 1)
        self.lAnalyzeOutpu = QtWidgets.QLabel(self.groupAnalyze)
        self.lAnalyzeOutpu.setEnabled(False)
        self.lAnalyzeOutpu.setObjectName("lAnalyzeOutpu")
        self.glAnalyze.addWidget(self.lAnalyzeOutpu, 1, 0, 1, 1)
        self.textAnalyzeInput = QtWidgets.QTextEdit(self.groupAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textAnalyzeInput.sizePolicy().hasHeightForWidth())
        self.textAnalyzeInput.setSizePolicy(sizePolicy)
        self.textAnalyzeInput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textAnalyzeInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textAnalyzeInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textAnalyzeInput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textAnalyzeInput.setObjectName("textAnalyzeInput")
        self.glAnalyze.addWidget(self.textAnalyzeInput, 0, 1, 1, 1)
        self.bpAnalyzeStart = QtWidgets.QPushButton(self.groupAnalyze)
        self.bpAnalyzeStart.setEnabled(True)
        self.bpAnalyzeStart.setObjectName("bpAnalyzeStart")
        self.glAnalyze.addWidget(self.bpAnalyzeStart, 2, 2, 1, 2)
        self.textAnalyzeOutput = QtWidgets.QTextEdit(self.groupAnalyze)
        self.textAnalyzeOutput.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textAnalyzeOutput.sizePolicy().hasHeightForWidth())
        self.textAnalyzeOutput.setSizePolicy(sizePolicy)
        self.textAnalyzeOutput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textAnalyzeOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textAnalyzeOutput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textAnalyzeOutput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textAnalyzeOutput.setObjectName("textAnalyzeOutput")
        self.glAnalyze.addWidget(self.textAnalyzeOutput, 1, 1, 1, 1)
        self.pbAnalyzeOpen = QtWidgets.QPushButton(self.groupAnalyze)
        self.pbAnalyzeOpen.setObjectName("pbAnalyzeOpen")
        self.glAnalyze.addWidget(self.pbAnalyzeOpen, 0, 2, 1, 1)
        self.bpAnalyzer = QtWidgets.QProgressBar(self.groupAnalyze)
        self.bpAnalyzer.setProperty("value", 0)
        self.bpAnalyzer.setObjectName("bpAnalyzer")
        self.glAnalyze.addWidget(self.bpAnalyzer, 2, 0, 1, 2)
        self.gridLayout_6.addLayout(self.glAnalyze, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupAnalyze, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.twCentral.addTab(self.tabProcess, "")
        self.tabTelemetry = QtWidgets.QWidget()
        self.tabTelemetry.setEnabled(False)
        self.tabTelemetry.setObjectName("tabTelemetry")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabTelemetry)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.vlTelemetry = QtWidgets.QVBoxLayout()
        self.vlTelemetry.setObjectName("vlTelemetry")
        self.twTelemetry = QtWidgets.QTabWidget(self.tabTelemetry)
        self.twTelemetry.setObjectName("twTelemetry")
        self.tabFrame = QtWidgets.QWidget()
        self.tabFrame.setObjectName("tabFrame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tabFrame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gropFrameInfo = QtWidgets.QGroupBox(self.tabFrame)
        self.gropFrameInfo.setObjectName("gropFrameInfo")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gropFrameInfo)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lFrameMajorFrame_2 = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameMajorFrame_2.setObjectName("lFrameMajorFrame_2")
        self.gridLayout_10.addWidget(self.lFrameMajorFrame_2, 3, 0, 1, 1)
        self.lFrameMinorFrame = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameMinorFrame.setObjectName("lFrameMinorFrame")
        self.gridLayout_10.addWidget(self.lFrameMinorFrame, 3, 2, 1, 1)
        self.lFrameSpacecraft = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameSpacecraft.setObjectName("lFrameSpacecraft")
        self.gridLayout_10.addWidget(self.lFrameSpacecraft, 1, 2, 1, 1)
        self.cbFrameMajorFrame = QtWidgets.QComboBox(self.gropFrameInfo)
        self.cbFrameMajorFrame.setObjectName("cbFrameMajorFrame")
        self.gridLayout_10.addWidget(self.cbFrameMajorFrame, 4, 0, 1, 2)
        self.lFrameMajorFrame = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameMajorFrame.setObjectName("lFrameMajorFrame")
        self.gridLayout_10.addWidget(self.lFrameMajorFrame, 1, 0, 1, 1)
        self.lFrameSpacecraftID = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameSpacecraftID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lFrameSpacecraftID.setObjectName("lFrameSpacecraftID")
        self.gridLayout_10.addWidget(self.lFrameSpacecraftID, 1, 3, 1, 1)
        self.cbFrameMinorFrame = QtWidgets.QComboBox(self.gropFrameInfo)
        self.cbFrameMinorFrame.setObjectName("cbFrameMinorFrame")
        self.gridLayout_10.addWidget(self.cbFrameMinorFrame, 4, 2, 1, 2)
        self.lFrameMajorFrameNum = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameMajorFrameNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lFrameMajorFrameNum.setObjectName("lFrameMajorFrameNum")
        self.gridLayout_10.addWidget(self.lFrameMajorFrameNum, 1, 1, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 3)
        self.gridLayout_10.setColumnStretch(1, 2)
        self.gridLayout_10.setColumnStretch(2, 3)
        self.gridLayout_10.setColumnStretch(3, 2)
        self.gridLayout_11.addWidget(self.gropFrameInfo, 0, 0, 1, 1)
        self.groupFrameDetail = QtWidgets.QGroupBox(self.tabFrame)
        self.groupFrameDetail.setObjectName("groupFrameDetail")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupFrameDetail)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lFrameTimestampText = QtWidgets.QLabel(self.groupFrameDetail)
        self.lFrameTimestampText.setObjectName("lFrameTimestampText")
        self.gridLayout_5.addWidget(self.lFrameTimestampText, 0, 0, 1, 1)
        self.lFrameScore = QtWidgets.QLabel(self.groupFrameDetail)
        self.lFrameScore.setObjectName("lFrameScore")
        self.gridLayout_5.addWidget(self.lFrameScore, 1, 1, 1, 1)
        self.lFrameScoreText = QtWidgets.QLabel(self.groupFrameDetail)
        self.lFrameScoreText.setObjectName("lFrameScoreText")
        self.gridLayout_5.addWidget(self.lFrameScoreText, 1, 0, 1, 1)
        self.lFrameTimestamp = QtWidgets.QLabel(self.groupFrameDetail)
        self.lFrameTimestamp.setObjectName("lFrameTimestamp")
        self.gridLayout_5.addWidget(self.lFrameTimestamp, 0, 1, 1, 1)
        self.textFrame = QtWidgets.QTextBrowser(self.groupFrameDetail)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans Mono")
        font.setPointSize(10)
        self.textFrame.setFont(font)
        self.textFrame.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textFrame.setObjectName("textFrame")
        self.gridLayout_5.addWidget(self.textFrame, 4, 0, 1, 5)
        self.lFrameFramesText = QtWidgets.QLabel(self.groupFrameDetail)
        self.lFrameFramesText.setObjectName("lFrameFramesText")
        self.gridLayout_5.addWidget(self.lFrameFramesText, 0, 2, 1, 1)
        self.lFrameFilteredText = QtWidgets.QLabel(self.groupFrameDetail)
        self.lFrameFilteredText.setObjectName("lFrameFilteredText")
        self.gridLayout_5.addWidget(self.lFrameFilteredText, 1, 2, 1, 1)
        self.lFrameFiltered = QtWidgets.QLabel(self.groupFrameDetail)
        self.lFrameFiltered.setObjectName("lFrameFiltered")
        self.gridLayout_5.addWidget(self.lFrameFiltered, 1, 3, 1, 1)
        self.lFrameFrames = QtWidgets.QLabel(self.groupFrameDetail)
        self.lFrameFrames.setObjectName("lFrameFrames")
        self.gridLayout_5.addWidget(self.lFrameFrames, 0, 3, 1, 1)
        self.gridLayout_5.setColumnMinimumWidth(1, 200)
        self.gridLayout_5.setColumnStretch(0, 3)
        self.gridLayout_5.setColumnStretch(1, 2)
        self.gridLayout_5.setColumnStretch(2, 3)
        self.gridLayout_5.setColumnStretch(3, 2)
        self.gridLayout_11.addWidget(self.groupFrameDetail, 1, 0, 1, 1)
        self.twTelemetry.addTab(self.tabFrame, "")
        self.tabStats = QtWidgets.QWidget()
        self.tabStats.setObjectName("tabStats")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabStats)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.wStats = QtWidgets.QWidget(self.tabStats)
        self.wStats.setObjectName("wStats")
        self.gridLayout_12.addWidget(self.wStats, 0, 0, 1, 1)
        self.twTelemetry.addTab(self.tabStats, "")
        self.tabSEM = QtWidgets.QWidget()
        self.tabSEM.setObjectName("tabSEM")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tabSEM)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.wSEM = QtWidgets.QWidget(self.tabSEM)
        self.wSEM.setObjectName("wSEM")
        self.gridLayout_13.addWidget(self.wSEM, 0, 0, 1, 1)
        self.twTelemetry.addTab(self.tabSEM, "")
        self.vlTelemetry.addWidget(self.twTelemetry)
        self.gridLayout_4.addLayout(self.vlTelemetry, 1, 0, 1, 1)
        self.twCentral.addTab(self.tabTelemetry, "")
        self.tbProcess = QtWidgets.QPlainTextEdit(self.splitter)
        self.tbProcess.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tbProcess.setFont(font)
        self.tbProcess.setReadOnly(True)
        self.tbProcess.setMaximumBlockCount(500)
        self.tbProcess.setObjectName("tbProcess")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicence = QtWidgets.QAction(MainWindow)
        self.actionLicence.setObjectName("actionLicence")
        self.actionConsole_Output = QtWidgets.QAction(MainWindow)
        self.actionConsole_Output.setCheckable(True)
        self.actionConsole_Output.setChecked(True)
        self.actionConsole_Output.setObjectName("actionConsole_Output")
        self.actionTelemetry = QtWidgets.QAction(MainWindow)
        self.actionTelemetry.setObjectName("actionTelemetry")
        self.actionDemod = QtWidgets.QAction(MainWindow)
        self.actionDemod.setObjectName("actionDemod")
        self.actionAnalyzer = QtWidgets.QAction(MainWindow)
        self.actionAnalyzer.setObjectName("actionAnalyzer")
        self.actionDecoder = QtWidgets.QAction(MainWindow)
        self.actionDecoder.setObjectName("actionDecoder")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLicence)
        self.menuSettings.addAction(self.actionConsole_Output)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionDemod)
        self.menuSettings.addAction(self.actionDecoder)
        self.menuSettings.addAction(self.actionAnalyzer)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.twCentral.setCurrentIndex(0)
        self.twTelemetry.setCurrentIndex(0)
        self.pbDemodOpen.clicked.connect(MainWindow.pbDemodOpen_clicked)
        self.pbDecodeOpen.clicked.connect(MainWindow.pbDecodeOpen_clicked)
        self.pbAnalyzeOpen.clicked.connect(MainWindow.pbAnalyzeOpen_clicked)
        self.pbDemodSelect.clicked.connect(MainWindow.pbDemodSelect_clicked)
        self.pbDecodeSelect.clicked.connect(MainWindow.pbDecodeSelect_clicked)
        self.bpAnalyzeSelect.clicked.connect(MainWindow.pbAnalyzeSelect_clicked)
        self.actionExit.triggered.connect(MainWindow.close)
        self.tbDemodSettings.clicked.connect(MainWindow.tbDemodSettings_clicked)
        self.tbDecodeSettings.clicked.connect(MainWindow.tbDecodeSettings_clicked)
        self.tbAnalyzeSettings.clicked.connect(MainWindow.tbAnalyzeSettings_clicked)
        self.pbDemodStart.clicked.connect(MainWindow.run_demod)
        self.pbDecodeStart.clicked.connect(MainWindow.run_decode)
        self.bpAnalyzeStart.clicked.connect(MainWindow.run_analyze)
        self.actionConsole_Output.toggled['bool'].connect(self.tbProcess.setVisible)
        self.actionAbout.triggered.connect(MainWindow.onAbout)
        self.actionLicence.triggered.connect(MainWindow.onLicense)
        self.cbFrameMajorFrame.currentIndexChanged['int'].connect(MainWindow.onMajorFrameChanged)
        self.cbFrameMinorFrame.currentIndexChanged['int'].connect(MainWindow.onMinorFrameChanged)
        self.actionAnalyzer.triggered.connect(MainWindow.tbAnalyzeSettings_clicked)
        self.actionDecoder.triggered.connect(MainWindow.tbDecodeSettings_clicked)
        self.actionDemod.triggered.connect(MainWindow.tbDemodSettings_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NOAA DSB Decoder"))
        self.groupDemod.setTitle(_translate("MainWindow", "Demodulator"))
        self.tbDemodSettings.setText(_translate("MainWindow", "..."))
        self.pbDemodStart.setText(_translate("MainWindow", "Demodulate"))
        self.pbDemodOpen.setText(_translate("MainWindow", "Open"))
        self.textDemodOutput.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bitstream Vera Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textDemodOutput.setPlaceholderText(_translate("MainWindow", "demod.raw"))
        self.pbDemodSelect.setText(_translate("MainWindow", "Select"))
        self.textDemodInput.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bitstream Vera Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textDemodInput.setPlaceholderText(_translate("MainWindow", "IQ-Record.raw"))
        self.lDemodInput.setText(_translate("MainWindow", "Input File"))
        self.lDemodOuput.setText(_translate("MainWindow", "Output File"))
        self.groupDecode.setTitle(_translate("MainWindow", "Decoder"))
        self.tbDecodeSettings.setText(_translate("MainWindow", "..."))
        self.pbDecodeStart.setText(_translate("MainWindow", "Decode"))
        self.pbDecodeOpen.setText(_translate("MainWindow", "Open"))
        self.textDecodeOutput.setPlaceholderText(_translate("MainWindow", "NOAA.txt"))
        self.pbDecodeSelect.setText(_translate("MainWindow", "Select"))
        self.textDecodeInput.setPlaceholderText(_translate("MainWindow", "demod.raw"))
        self.lDecodeInput.setText(_translate("MainWindow", "Input File"))
        self.lDecodeOutput.setText(_translate("MainWindow", "Output File"))
        self.groupAnalyze.setTitle(_translate("MainWindow", "Analyzer"))
        self.tbAnalyzeSettings.setText(_translate("MainWindow", "..."))
        self.bpAnalyzeSelect.setText(_translate("MainWindow", "Select"))
        self.lAnalyzeInput.setText(_translate("MainWindow", "Input File"))
        self.lAnalyzeOutpu.setText(_translate("MainWindow", "Output File"))
        self.textAnalyzeInput.setPlaceholderText(_translate("MainWindow", "NOAA.txt"))
        self.bpAnalyzeStart.setText(_translate("MainWindow", "Analyze"))
        self.textAnalyzeOutput.setPlaceholderText(_translate("MainWindow", "Telemetry.txt"))
        self.pbAnalyzeOpen.setText(_translate("MainWindow", "Open"))
        self.twCentral.setTabText(self.twCentral.indexOf(self.tabProcess), _translate("MainWindow", "Process"))
        self.gropFrameInfo.setTitle(_translate("MainWindow", "Info"))
        self.lFrameMajorFrame_2.setText(_translate("MainWindow", "Major Frame"))
        self.lFrameMinorFrame.setText(_translate("MainWindow", "Minor Frame"))
        self.lFrameSpacecraft.setText(_translate("MainWindow", "Spacecraft:"))
        self.lFrameMajorFrame.setText(_translate("MainWindow", "#Major Frames"))
        self.lFrameSpacecraftID.setText(_translate("MainWindow", "NOAA-19 (N\')"))
        self.lFrameMajorFrameNum.setText(_translate("MainWindow", "6331"))
        self.groupFrameDetail.setTitle(_translate("MainWindow", "Detail"))
        self.lFrameTimestampText.setText(_translate("MainWindow", "Timestamp"))
        self.lFrameScore.setText(_translate("MainWindow", "100%"))
        self.lFrameScoreText.setText(_translate("MainWindow", "Score"))
        self.lFrameTimestamp.setText(_translate("MainWindow", "None"))
        self.textFrame.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bitstream Vera Sans Mono\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Bitstream Vera Sans\'; font-size:12pt;\"><br /></p></body></html>"))
        self.lFrameFramesText.setText(_translate("MainWindow", "Frames"))
        self.lFrameFilteredText.setText(_translate("MainWindow", "Filtered Frames"))
        self.lFrameFiltered.setText(_translate("MainWindow", "0"))
        self.lFrameFrames.setText(_translate("MainWindow", "0"))
        self.twTelemetry.setTabText(self.twTelemetry.indexOf(self.tabFrame), _translate("MainWindow", "Frame"))
        self.twTelemetry.setTabText(self.twTelemetry.indexOf(self.tabStats), _translate("MainWindow", "Statistics"))
        self.twTelemetry.setTabText(self.twTelemetry.indexOf(self.tabSEM), _translate("MainWindow", "SEM"))
        self.twCentral.setTabText(self.twCentral.indexOf(self.tabTelemetry), _translate("MainWindow", "Telemetry"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLicence.setText(_translate("MainWindow", "Licence"))
        self.actionConsole_Output.setText(_translate("MainWindow", "Console Output"))
        self.actionTelemetry.setText(_translate("MainWindow", "Telemetry"))
        self.actionDemod.setText(_translate("MainWindow", "Demodulator"))
        self.actionAnalyzer.setText(_translate("MainWindow", "Analyzer"))
        self.actionDecoder.setText(_translate("MainWindow", "Decoder"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
