# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 576)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(458, 528))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.twCentral = QtWidgets.QTabWidget(self.centralwidget)
        self.twCentral.setEnabled(True)
        self.twCentral.setTabsClosable(False)
        self.twCentral.setTabBarAutoHide(False)
        self.twCentral.setObjectName("twCentral")
        self.tabProcess = QtWidgets.QWidget()
        self.tabProcess.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabProcess.sizePolicy().hasHeightForWidth())
        self.tabProcess.setSizePolicy(sizePolicy)
        self.tabProcess.setObjectName("tabProcess")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabProcess)
        self.gridLayout_5.setContentsMargins(9, -1, 9, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vlProcess = QtWidgets.QVBoxLayout()
        self.vlProcess.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.vlProcess.setObjectName("vlProcess")
        self.groupDemod = QtWidgets.QGroupBox(self.tabProcess)
        self.groupDemod.setObjectName("groupDemod")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupDemod)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.glDemod = QtWidgets.QGridLayout()
        self.glDemod.setObjectName("glDemod")
        self.tbDemodSettings = QtWidgets.QToolButton(self.groupDemod)
        self.tbDemodSettings.setObjectName("tbDemodSettings")
        self.glDemod.addWidget(self.tbDemodSettings, 0, 3, 1, 1)
        self.pbDemodStart = QtWidgets.QPushButton(self.groupDemod)
        self.pbDemodStart.setObjectName("pbDemodStart")
        self.glDemod.addWidget(self.pbDemodStart, 2, 2, 1, 2)
        self.pbDemodOpen = QtWidgets.QPushButton(self.groupDemod)
        self.pbDemodOpen.setObjectName("pbDemodOpen")
        self.glDemod.addWidget(self.pbDemodOpen, 0, 2, 1, 1)
        self.textDemodOutput = QtWidgets.QTextEdit(self.groupDemod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textDemodOutput.sizePolicy().hasHeightForWidth())
        self.textDemodOutput.setSizePolicy(sizePolicy)
        self.textDemodOutput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textDemodOutput.setObjectName("textDemodOutput")
        self.glDemod.addWidget(self.textDemodOutput, 1, 1, 1, 1)
        self.pbDemodSelect = QtWidgets.QPushButton(self.groupDemod)
        self.pbDemodSelect.setObjectName("pbDemodSelect")
        self.glDemod.addWidget(self.pbDemodSelect, 1, 2, 1, 1)
        self.textDemodInput = QtWidgets.QTextEdit(self.groupDemod)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textDemodInput.sizePolicy().hasHeightForWidth())
        self.textDemodInput.setSizePolicy(sizePolicy)
        self.textDemodInput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textDemodInput.setObjectName("textDemodInput")
        self.glDemod.addWidget(self.textDemodInput, 0, 1, 1, 1)
        self.lDemodInput = QtWidgets.QLabel(self.groupDemod)
        self.lDemodInput.setObjectName("lDemodInput")
        self.glDemod.addWidget(self.lDemodInput, 0, 0, 1, 1)
        self.lDemodOuput = QtWidgets.QLabel(self.groupDemod)
        self.lDemodOuput.setObjectName("lDemodOuput")
        self.glDemod.addWidget(self.lDemodOuput, 1, 0, 1, 1)
        self.pbDemod = QtWidgets.QProgressBar(self.groupDemod)
        self.pbDemod.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.pbDemod.setProperty("value", 10)
        self.pbDemod.setObjectName("pbDemod")
        self.glDemod.addWidget(self.pbDemod, 2, 0, 1, 2)
        self.gridLayout_8.addLayout(self.glDemod, 0, 0, 1, 1)
        self.vlProcess.addWidget(self.groupDemod)
        self.groupDecode = QtWidgets.QGroupBox(self.tabProcess)
        self.groupDecode.setObjectName("groupDecode")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupDecode)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.glDecode = QtWidgets.QGridLayout()
        self.glDecode.setObjectName("glDecode")
        self.tbDecodeSettings = QtWidgets.QToolButton(self.groupDecode)
        self.tbDecodeSettings.setObjectName("tbDecodeSettings")
        self.glDecode.addWidget(self.tbDecodeSettings, 0, 3, 1, 1)
        self.pbDecodeStart = QtWidgets.QPushButton(self.groupDecode)
        self.pbDecodeStart.setObjectName("pbDecodeStart")
        self.glDecode.addWidget(self.pbDecodeStart, 2, 2, 1, 2)
        self.pbDecodeOpen = QtWidgets.QPushButton(self.groupDecode)
        self.pbDecodeOpen.setObjectName("pbDecodeOpen")
        self.glDecode.addWidget(self.pbDecodeOpen, 0, 2, 1, 1)
        self.textDecodeOutput = QtWidgets.QTextEdit(self.groupDecode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textDecodeOutput.sizePolicy().hasHeightForWidth())
        self.textDecodeOutput.setSizePolicy(sizePolicy)
        self.textDecodeOutput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textDecodeOutput.setObjectName("textDecodeOutput")
        self.glDecode.addWidget(self.textDecodeOutput, 1, 1, 1, 1)
        self.pbDecodeSelect = QtWidgets.QPushButton(self.groupDecode)
        self.pbDecodeSelect.setObjectName("pbDecodeSelect")
        self.glDecode.addWidget(self.pbDecodeSelect, 1, 2, 1, 1)
        self.textDecodeInput = QtWidgets.QTextEdit(self.groupDecode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textDecodeInput.sizePolicy().hasHeightForWidth())
        self.textDecodeInput.setSizePolicy(sizePolicy)
        self.textDecodeInput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textDecodeInput.setObjectName("textDecodeInput")
        self.glDecode.addWidget(self.textDecodeInput, 0, 1, 1, 1)
        self.lDecodeInput = QtWidgets.QLabel(self.groupDecode)
        self.lDecodeInput.setObjectName("lDecodeInput")
        self.glDecode.addWidget(self.lDecodeInput, 0, 0, 1, 1)
        self.lDecodeOutput = QtWidgets.QLabel(self.groupDecode)
        self.lDecodeOutput.setObjectName("lDecodeOutput")
        self.glDecode.addWidget(self.lDecodeOutput, 1, 0, 1, 1)
        self.pbDecode = QtWidgets.QProgressBar(self.groupDecode)
        self.pbDecode.setProperty("value", 24)
        self.pbDecode.setObjectName("pbDecode")
        self.glDecode.addWidget(self.pbDecode, 2, 0, 1, 2)
        self.gridLayout_7.addLayout(self.glDecode, 0, 0, 1, 1)
        self.vlProcess.addWidget(self.groupDecode)
        self.groupAnalyze = QtWidgets.QGroupBox(self.tabProcess)
        self.groupAnalyze.setObjectName("groupAnalyze")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupAnalyze)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.glAnalyze = QtWidgets.QGridLayout()
        self.glAnalyze.setObjectName("glAnalyze")
        self.tpAnalyzeSettings = QtWidgets.QToolButton(self.groupAnalyze)
        self.tpAnalyzeSettings.setObjectName("tpAnalyzeSettings")
        self.glAnalyze.addWidget(self.tpAnalyzeSettings, 0, 3, 1, 1)
        self.bpAnalyzeStart = QtWidgets.QPushButton(self.groupAnalyze)
        self.bpAnalyzeStart.setObjectName("bpAnalyzeStart")
        self.glAnalyze.addWidget(self.bpAnalyzeStart, 2, 2, 1, 2)
        self.pbAnalyzeOpen = QtWidgets.QPushButton(self.groupAnalyze)
        self.pbAnalyzeOpen.setObjectName("pbAnalyzeOpen")
        self.glAnalyze.addWidget(self.pbAnalyzeOpen, 0, 2, 1, 1)
        self.textAnalyzeOutput = QtWidgets.QTextEdit(self.groupAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textAnalyzeOutput.sizePolicy().hasHeightForWidth())
        self.textAnalyzeOutput.setSizePolicy(sizePolicy)
        self.textAnalyzeOutput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textAnalyzeOutput.setObjectName("textAnalyzeOutput")
        self.glAnalyze.addWidget(self.textAnalyzeOutput, 1, 1, 1, 1)
        self.bpAnalyzeSelect = QtWidgets.QPushButton(self.groupAnalyze)
        self.bpAnalyzeSelect.setObjectName("bpAnalyzeSelect")
        self.glAnalyze.addWidget(self.bpAnalyzeSelect, 1, 2, 1, 1)
        self.textAnalyzeInput = QtWidgets.QTextEdit(self.groupAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textAnalyzeInput.sizePolicy().hasHeightForWidth())
        self.textAnalyzeInput.setSizePolicy(sizePolicy)
        self.textAnalyzeInput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textAnalyzeInput.setObjectName("textAnalyzeInput")
        self.glAnalyze.addWidget(self.textAnalyzeInput, 0, 1, 1, 1)
        self.lAnalyzeInput = QtWidgets.QLabel(self.groupAnalyze)
        self.lAnalyzeInput.setObjectName("lAnalyzeInput")
        self.glAnalyze.addWidget(self.lAnalyzeInput, 0, 0, 1, 1)
        self.lAnalyzeOutpu = QtWidgets.QLabel(self.groupAnalyze)
        self.lAnalyzeOutpu.setObjectName("lAnalyzeOutpu")
        self.glAnalyze.addWidget(self.lAnalyzeOutpu, 1, 0, 1, 1)
        self.pbAnalyze = QtWidgets.QProgressBar(self.groupAnalyze)
        self.pbAnalyze.setProperty("value", 99)
        self.pbAnalyze.setObjectName("pbAnalyze")
        self.glAnalyze.addWidget(self.pbAnalyze, 2, 0, 1, 2)
        self.gridLayout_6.addLayout(self.glAnalyze, 0, 0, 1, 1)
        self.vlProcess.addWidget(self.groupAnalyze)
        self.gridLayout_5.addLayout(self.vlProcess, 0, 0, 1, 1)
        self.twCentral.addTab(self.tabProcess, "")
        self.tabTelemetry = QtWidgets.QWidget()
        self.tabTelemetry.setObjectName("tabTelemetry")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabTelemetry)
        self.gridLayout_9.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.vlTelemetry = QtWidgets.QVBoxLayout()
        self.vlTelemetry.setObjectName("vlTelemetry")
        self.twTelemetry = QtWidgets.QTabWidget(self.tabTelemetry)
        self.twTelemetry.setObjectName("twTelemetry")
        self.tabFrame = QtWidgets.QWidget()
        self.tabFrame.setObjectName("tabFrame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tabFrame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gropFrameInfo = QtWidgets.QGroupBox(self.tabFrame)
        self.gropFrameInfo.setObjectName("gropFrameInfo")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gropFrameInfo)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lFrameSpacecraftID = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameSpacecraftID.setObjectName("lFrameSpacecraftID")
        self.gridLayout_10.addWidget(self.lFrameSpacecraftID, 0, 3, 1, 1)
        self.lFrameMajorFrame = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameMajorFrame.setObjectName("lFrameMajorFrame")
        self.gridLayout_10.addWidget(self.lFrameMajorFrame, 0, 0, 1, 1)
        self.lFrameMajorFrame_2 = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameMajorFrame_2.setObjectName("lFrameMajorFrame_2")
        self.gridLayout_10.addWidget(self.lFrameMajorFrame_2, 2, 0, 1, 1)
        self.lFrameSpacecraft = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameSpacecraft.setObjectName("lFrameSpacecraft")
        self.gridLayout_10.addWidget(self.lFrameSpacecraft, 0, 2, 1, 1)
        self.lFrameMajorFrameNum = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameMajorFrameNum.setObjectName("lFrameMajorFrameNum")
        self.gridLayout_10.addWidget(self.lFrameMajorFrameNum, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem, 1, 0, 1, 4)
        self.lFrameMinorFrame = QtWidgets.QLabel(self.gropFrameInfo)
        self.lFrameMinorFrame.setObjectName("lFrameMinorFrame")
        self.gridLayout_10.addWidget(self.lFrameMinorFrame, 2, 2, 1, 1)
        self.cbFrameMinorFrame = QtWidgets.QComboBox(self.gropFrameInfo)
        self.cbFrameMinorFrame.setObjectName("cbFrameMinorFrame")
        self.gridLayout_10.addWidget(self.cbFrameMinorFrame, 3, 2, 1, 2)
        self.cbFrameMajorFrame = QtWidgets.QComboBox(self.gropFrameInfo)
        self.cbFrameMajorFrame.setObjectName("cbFrameMajorFrame")
        self.gridLayout_10.addWidget(self.cbFrameMajorFrame, 3, 0, 1, 2)
        self.gridLayout_10.setColumnStretch(0, 3)
        self.gridLayout_10.setColumnStretch(1, 2)
        self.gridLayout_10.setColumnStretch(2, 3)
        self.gridLayout_10.setColumnStretch(3, 2)
        self.gridLayout_11.addWidget(self.gropFrameInfo, 0, 0, 1, 1)
        self.groupFrameDetail = QtWidgets.QGroupBox(self.tabFrame)
        self.groupFrameDetail.setObjectName("groupFrameDetail")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupFrameDetail)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tvFrameDetail = QtWidgets.QTableView(self.groupFrameDetail)
        self.tvFrameDetail.setObjectName("tvFrameDetail")
        self.verticalLayout_5.addWidget(self.tvFrameDetail)
        self.gridLayout_11.addWidget(self.groupFrameDetail, 1, 0, 1, 1)
        self.twTelemetry.addTab(self.tabFrame, "")
        self.tabStats = QtWidgets.QWidget()
        self.tabStats.setObjectName("tabStats")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabStats)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.wStats = QtWidgets.QWidget(self.tabStats)
        self.wStats.setObjectName("wStats")
        self.gridLayout_12.addWidget(self.wStats, 0, 0, 1, 1)
        self.twTelemetry.addTab(self.tabStats, "")
        self.tabSEM = QtWidgets.QWidget()
        self.tabSEM.setObjectName("tabSEM")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tabSEM)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.wSEM = QtWidgets.QWidget(self.tabSEM)
        self.wSEM.setObjectName("wSEM")
        self.gridLayout_13.addWidget(self.wSEM, 0, 0, 1, 1)
        self.twTelemetry.addTab(self.tabSEM, "")
        self.vlTelemetry.addWidget(self.twTelemetry)
        self.gridLayout_9.addLayout(self.vlTelemetry, 0, 0, 1, 1)
        self.twCentral.addTab(self.tabTelemetry, "")
        self.horizontalLayout.addWidget(self.twCentral)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicence = QtWidgets.QAction(MainWindow)
        self.actionLicence.setObjectName("actionLicence")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLicence)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.twCentral.setCurrentIndex(1)
        self.twTelemetry.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NOAA DSB Decoder"))
        self.groupDemod.setTitle(_translate("MainWindow", "Demodulate"))
        self.tbDemodSettings.setText(_translate("MainWindow", "..."))
        self.pbDemodStart.setText(_translate("MainWindow", "Demodulate"))
        self.pbDemodOpen.setText(_translate("MainWindow", "Open"))
        self.pbDemodSelect.setText(_translate("MainWindow", "Select"))
        self.lDemodInput.setText(_translate("MainWindow", "Input File"))
        self.lDemodOuput.setText(_translate("MainWindow", "Output File"))
        self.groupDecode.setTitle(_translate("MainWindow", "Decode"))
        self.tbDecodeSettings.setText(_translate("MainWindow", "..."))
        self.pbDecodeStart.setText(_translate("MainWindow", "Decode"))
        self.pbDecodeOpen.setText(_translate("MainWindow", "Open"))
        self.pbDecodeSelect.setText(_translate("MainWindow", "Select"))
        self.lDecodeInput.setText(_translate("MainWindow", "Input File"))
        self.lDecodeOutput.setText(_translate("MainWindow", "Output File"))
        self.groupAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.tpAnalyzeSettings.setText(_translate("MainWindow", "..."))
        self.bpAnalyzeStart.setText(_translate("MainWindow", "Analyze"))
        self.pbAnalyzeOpen.setText(_translate("MainWindow", "Open"))
        self.bpAnalyzeSelect.setText(_translate("MainWindow", "Select"))
        self.lAnalyzeInput.setText(_translate("MainWindow", "Input File"))
        self.lAnalyzeOutpu.setText(_translate("MainWindow", "Output File"))
        self.twCentral.setTabText(self.twCentral.indexOf(self.tabProcess), _translate("MainWindow", "Process"))
        self.gropFrameInfo.setTitle(_translate("MainWindow", "Info"))
        self.lFrameSpacecraftID.setText(_translate("MainWindow", "NOAA-19 (N\')"))
        self.lFrameMajorFrame.setText(_translate("MainWindow", "#Major Frames"))
        self.lFrameMajorFrame_2.setText(_translate("MainWindow", "Major Frame"))
        self.lFrameSpacecraft.setText(_translate("MainWindow", "Spacecraft:"))
        self.lFrameMajorFrameNum.setText(_translate("MainWindow", "6331"))
        self.lFrameMinorFrame.setText(_translate("MainWindow", "Minor Frame"))
        self.groupFrameDetail.setTitle(_translate("MainWindow", "Detail"))
        self.twTelemetry.setTabText(self.twTelemetry.indexOf(self.tabFrame), _translate("MainWindow", "Frame"))
        self.twTelemetry.setTabText(self.twTelemetry.indexOf(self.tabStats), _translate("MainWindow", "Statistics"))
        self.twTelemetry.setTabText(self.twTelemetry.indexOf(self.tabSEM), _translate("MainWindow", "SEM"))
        self.twCentral.setTabText(self.twCentral.indexOf(self.tabTelemetry), _translate("MainWindow", "Telemetry"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLicence.setText(_translate("MainWindow", "Licence"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
