% Script generated by antennaDesigner 
% Define plot frequency 
plotFrequency = 137500000;
% Define frequency range 
freqRange = (123.75:1.375:151.25) * 1e6;
% Define antenna 
antennaObject = dipoleVee_antennaDesigner;
% show for dipoleVee
figure;
show(antennaObject) 
% impedance for dipoleVee
figure;
impedance(antennaObject, freqRange) 
% pattern for dipoleVee
figure;
pattern(antennaObject, plotFrequency) 
% s11 for dipoleVee
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 
figure;
patternElevation(antennaObject, plotFrequency) 

